# Generated by Django 5.1.1 on 2024-10-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Купон')),
                ('sale', models.IntegerField(verbose_name='Размер скидки')),
                ('count', models.IntegerField(verbose_name='Количество купонов')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='BoostOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.CharField(choices=[('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Голд'), ('PLATINUM', 'Платина'), ('EMERALD', 'Эмеральд'), ('DIAMOND', 'Даймонд'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Грандмастер')], max_length=20, verbose_name='Текущий ранг')),
                ('current_division', models.CharField(choices=[('DIVISION 1', 'Дивизион 1'), ('DIVISION 2', 'Дивизион 2'), ('DIVISION 3', 'Дивизион 3'), ('DIVISION 4', 'Дивизион 4')], max_length=20, verbose_name='Текущий дивизион')),
                ('current_lp', models.CharField(choices=[('0-20LP', '0-20LP'), ('21-40LP', '21-40LP'), ('41-60LP', '41-60LP'), ('61-80LP', '61-80LP'), ('81-99LP', '81-99LP')], max_length=20, verbose_name='Текущие лп')),
                ('desired_position', models.CharField(choices=[('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Голд'), ('PLATINUM', 'Платина'), ('EMERALD', 'Эмеральд'), ('DIAMOND', 'Даймонд'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Грандмастер')], max_length=20, verbose_name='Желаемый ранг')),
                ('desired_division', models.CharField(choices=[('DIVISION 1', 'Дивизион 1'), ('DIVISION 2', 'Дивизион 2'), ('DIVISION 3', 'Дивизион 3'), ('DIVISION 4', 'Дивизион 4')], max_length=20, verbose_name='Желаемый дивизион')),
                ('lp_per_win', models.CharField(choices=[('18+LP', '18+ LP'), ('15-17LP', '15-17 LP'), ('<15LP', '<15LP')], max_length=20, verbose_name='ЛП за победу')),
                ('server', models.CharField(choices=[('EU WEST', 'Вест'), ('RUSSIA', 'Россия')], max_length=20, verbose_name='Сервер')),
                ('queue_type', models.CharField(choices=[('SOLO/DUO', 'Соло-дуо'), ('FLEX', 'Флекс')], max_length=20, verbose_name='Режим игры')),
                ('specific_role', models.BooleanField(verbose_name='Определенная роль')),
                ('duo_booster', models.BooleanField(verbose_name='Игра в дуо')),
                ('total_time', models.DurationField(verbose_name='Время исполнения')),
                ('total_price', models.IntegerField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_orders', to='store.coupon', verbose_name='Купон')),
            ],
            options={
                'verbose_name': 'Буст ордер',
                'verbose_name_plural': 'Буст ордеры',
            },
        ),
    ]
