# Generated by Django 5.1.1 on 2024-10-26 15:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='count',
            field=models.IntegerField(default=999, verbose_name='Количество купонов'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_position', models.CharField(choices=[('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Голд'), ('PLATINUM', 'Платина'), ('EMERALD', 'Эмеральд'), ('DIAMOND', 'Даймонд'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Грандмастер')], max_length=20, verbose_name='Ранг в прошлом сезоне')),
                ('specific_role', models.BooleanField(verbose_name='Определенная роль')),
                ('duo_booster', models.BooleanField(verbose_name='Игра в дуо')),
                ('game_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Кол-во игр')),
                ('server', models.CharField(choices=[('EU WEST', 'Вест'), ('RUSSIA', 'Россия')], max_length=20, verbose_name='Сервер')),
                ('queue_type', models.CharField(choices=[('SOLO/DUO', 'Соло-дуо'), ('FLEX', 'Флекс')], max_length=20, verbose_name='Режим игры')),
                ('total_time', models.DurationField(verbose_name='Время исполнения')),
                ('total_price', models.IntegerField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_orders', to='store.coupon', verbose_name='Купон')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
    ]
