# Generated by Django 5.1.1 on 2024-11-02 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_is_active_alter_coupon_count_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=20, verbose_name='Персонаж')),
                ('skin_name', models.CharField(max_length=20, verbose_name='Образ')),
                ('price_char', models.IntegerField(verbose_name='Цена персонажа')),
                ('price_skin', models.IntegerField(verbose_name='Цена образа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skins_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Скины и персонажи',
                'verbose_name_plural': 'Скины и персонажи',
            },
        ),
    ]
