# Generated by Django 5.1.1 on 2024-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_skinsorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinsorder',
            name='price_char',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена персонажа'),
        ),
        migrations.AlterField(
            model_name='skinsorder',
            name='price_skin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена образа'),
        ),
    ]
