# Generated by Django 5.1.1 on 2024-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_skinsorder_price_char_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinsorder',
            name='account_name',
            field=models.CharField(default='default_name', max_length=50, verbose_name='Никнейм аккаунта'),
        ),
        migrations.AddField(
            model_name='skinsorder',
            name='server',
            field=models.CharField(choices=[('EU WEST', 'Вест'), ('RUSSIA', 'Россия')], default='EU WEST', max_length=20, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='skinsorder',
            name='char_name',
            field=models.CharField(max_length=50, verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='skinsorder',
            name='skin_name',
            field=models.CharField(max_length=50, verbose_name='Образ'),
        ),
    ]
