# Generated by Django 5.1.1 on 2024-11-06 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_skinsorder_account_name_skinsorder_server_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RPorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.IntegerField(verbose_name='Кол-во RP')),
                ('price_rub', models.IntegerField(verbose_name='Цена')),
                ('server', models.CharField(choices=[('EU WEST', 'Вест'), ('RUSSIA', 'Россия')], default='EU WEST', max_length=20, verbose_name='Сервер')),
                ('account_name', models.CharField(default='default_name', max_length=50, verbose_name='Никнейм аккаунта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Риот Поинты',
                'verbose_name_plural': 'Риот Поинты',
            },
        ),
    ]
