# Generated by Django 5.1.1 on 2024-11-08 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rporder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('EU WEST', 'Вест'), ('RUSSIA', 'Россия')], default='EU WEST', max_length=20, verbose_name='Сервер')),
                ('lvl', models.IntegerField(verbose_name='Уровень')),
                ('champions', models.IntegerField(verbose_name='Количество чемпионов')),
                ('skins', models.IntegerField(verbose_name='Количество образов')),
                ('rang', models.CharField(default='Нет ранга', max_length=20, verbose_name='Ранг')),
                ('short_description', models.CharField(max_length=150, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Проверен')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acounts_objects', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Продажа аккаунта',
                'verbose_name_plural': 'Продажа аккаунтов',
            },
        ),
        migrations.CreateModel(
            name='AccountOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_order', to='store.accountobject', verbose_name='Аккаунт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acounts_orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ аккаунта',
                'verbose_name_plural': 'Заказы аккаунтов',
            },
        ),
        migrations.CreateModel(
            name='AccountsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/acounts_images/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.accountobject')),
            ],
            options={
                'verbose_name': 'Изображение для аккаунта',
                'verbose_name_plural': 'Изображения для аккаунтов',
            },
        ),
    ]
