# Generated by Django 5.1.1 on 2024-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_chatroom_buyer_alter_chatroom_seller_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='group_name',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
