# Generated by Django 5.1.1 on 2024-11-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_message_options_rename_sender_message_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='group_name',
        ),
    ]
