# Generated by Django 5.1.1 on 2024-11-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_chatroom_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='account_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='acount_chat_rooms', to='store.accountobject'),
        ),
    ]
