# Generated by Django 5.1.1 on 2024-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_account_id_chatroom_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountobject',
            name='rang',
            field=models.CharField(choices=[('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Голд'), ('PLATINUM', 'Платина'), ('EMERALD', 'Эмеральд'), ('DIAMOND', 'Даймонд'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Грандмастер')], default='Нет ранга', max_length=20, verbose_name='Ранг'),
        ),
    ]
