# Generated by Django 5.1.1 on 2024-11-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_accountobject_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountobject',
            name='rang',
            field=models.CharField(choices=[('NO RANK', 'Нет ранга'), ('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Голд'), ('PLATINUM', 'Платина'), ('EMERALD', 'Эмеральд'), ('DIAMOND', 'Даймонд'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Грандмастер')], default='NO RANK', max_length=20, verbose_name='Ранг'),
        ),
    ]
