# Generated by Django 5.1.1 on 2024-11-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_accountobject_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountobject',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Покупка подтверждена'),
        ),
    ]
