# Generated by Django 5.1.1 on 2024-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_accountobject_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='massage_type',
            field=models.CharField(blank=True, choices=[('chat_message', 'сообщение'), ('buy_account', 'бронирование аккаунта'), ('buy_account_acept', 'подтверждение покупки')], null=True, verbose_name='Тип сообщения'),
        ),
    ]
