# Generated by Django 5.1.1 on 2024-11-29 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_reviewsellermodel_buyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountobject',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acounts_buyer_objects', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
