# Generated by Django 5.1.1 on 2024-12-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acount_chat_rooms', to='store.accountobject'),
        ),
    ]
