# Generated by Django 5.1.1 on 2024-12-11 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_chatroom_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acount_chat_rooms', to='store.accountobject'),
        ),
    ]
