# Generated by Django 5.1.1 on 2024-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_chatroom_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountobject',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
