# Generated by Django 5.1.1 on 2024-12-20 07:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_accountobject_is_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountobject',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
    ]
