# Generated by Django 5.1.1 on 2024-12-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_message_massage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountobject',
            name='rang',
            field=models.CharField(choices=[('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Голд'), ('PLATINUM', 'Платина'), ('EMERALD', 'Эмеральд'), ('DIAMOND', 'Даймонд'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Грандмастер')], default='NO RANK', max_length=20, verbose_name='Ранг'),
        ),
    ]
