# Generated by Django 5.1.1 on 2024-12-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date_published',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
