# Generated by Django 5.1.1 on 2024-11-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reviewmodel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='reviews',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
