# Generated by Django 5.1.1 on 2024-12-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reviewmodel_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='reviews',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
    ]
