# Generated by Django 5.1.1 on 2024-12-20 07:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reviewmodel_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='reviews',
            field=tinymce.models.HTMLField(max_length=300, verbose_name='Описание'),
        ),
    ]
