# Generated by Django 5.1.1 on 2024-12-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reviewmodel_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], verbose_name='Оценка'),
        ),
    ]
