# Generated by Django 5.1.1 on 2024-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_reviewmodel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Оценка'),
        ),
    ]
