# Generated by Django 5.1.1 on 2024-10-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
