# Generated by Django 5.1.1 on 2024-11-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='users_avatar', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дискорд'),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Никнейм в игре'),
        ),
    ]
