# Generated by Django 5.1.1 on 2024-12-04 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_balance_alter_user_avatar_alter_user_discord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Дискорд'),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Никнейм в игре'),
        ),
    ]
