# Generated by Django 5.1.1 on 2024-12-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_balance_alter_user_discord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_username',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Никнейм в игре'),
        ),
    ]
